### ISSUE TITLE
タスクマップ

### ISSUE THREAD

**Issue by mihye1128** [mihye1128/tedori#1]
## 環境構築・初期設定

- [x] Prettier 実装 #2
- [x] AngularMaterial インストール・テーマカラー設定 #3
- [x] AngularFire インストール・FireBase連携 #4
- [x] レイアウト作成 #5

## 画面一覧

- [x] ホーム画面(home) #6 
- [x] マイページ画面(mypage) #7 
- [x] サービスLP画面(about) #8 
- [x] プライバシーポリシー画面(privacy) #9
- [x] 利用規約画面(terms) #10
- [x] 404画面(not-found) #11

## 機能一覧
- [x] 総支給額 計算(pay) #12 
- [x] 社会保険料 計算(social-ins) #13 
- [x] 労働保険料 計算(labor-ins) #14 
- [x] 源泉所得税 計算(natinal-tax) #15 
- [x] 差引支給額 計算(result) #16 
- [x] Googleアカウント認証機能(auth) #17 
- [x] formのバリデータ #18 

## 公開作業
- [x] META設定 #70 
- [x] PWA #72
