### ISSUE TITLE
公開準備

### ISSUE THREAD

**Issue by mihye1128** [mihye1128/tedori#132]
- [x] Material感減らす #133 
- [x] ディレクトリ設計変更・ナビゲーション追加 #135 
- [x] アイコン・スクリーンショット差し替え・画像圧縮 #137 
- [x] ng update #139 
- [x] bottomナビ実装 #141
- [x] Firebase・Algolia 開発環境と本番環境の切り分け #143 
- [x] 本番環境 ホスティング
- [x] AOS バグ修正 #147 
- [x] パネル開閉アニメーション実装 #149 
- [x] headerナビゲーションスタイル修正 #150
- [x] Github Actions devとprodそれぞれ実装 #151 
- [x] noindex削除 #157
